version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: wednesday 
      time: "18:40"
      timezone: Europe/London
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      production-dependencies:
        dependency-type: production
      development-tooling:
        dependency-type: development
